import { api } from '@/lib/api';

// ============================================
// Caiso - Costs Service (Módulo Custos)
// ============================================

export type CostCategory = 
  | 'FIXED'
  | 'VARIABLE'
  | 'PERSONNEL'
  | 'INFRASTRUCTURE'
  | 'EQUIPMENT'
  | 'MATERIAL'
  | 'SERVICES'
  | 'OTHER';

export interface Cost {
  id: string;
  category: CostCategory;
  description: string;
  amount: number;
  period: string;
  supplierId?: string;
  companyId?: string;
  instructorId?: string;
  linkType?: 'none' | 'company' | 'instructor';
  isRecurring: boolean;
  isAuditable: boolean;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CostCriterion {
  id: string;
  code: string;
  name: string;
  frequency: 'Monthly' | 'Daily' | 'OneTime';
  linkage: 'EnrolledStudent' | 'NotLinked' | 'Instructor';
  dueCriterion:
    | 'CourseEndDate'
    | '30DaysAfterEnd'
    | 'MonthlyClosing'
    | 'SpecificDate'
    | 'NoDue';
  daysUntilDue?: number;
  monthlyClosingDay?: number;
  daysAfterClosing?: number;
  triggers?: string[];
  active: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CostEntry {
  id: string;
  code: string;
  auditableCostId: string;
  costCriterionId?: string;
  studentId?: string;
  classId?: string;
  supplierId?: string;
  instructorId?: string;
  companyId?: string;
  examNumber?: string;
  examName?: string;
  value: number;
  generatedAt: string;
  dueDate: string;
  paidAt?: string;
  status: 'Pending' | 'Paid' | 'Overdue' | 'Cancelled';
  notes?: string;
  autoGenerated: boolean;
  triggerAction?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCostEntryDTO {
  id?: string;
  code: string;
  auditableCostId: string;
  costCriterionId?: string;
  studentId?: string;
  classId?: string;
  supplierId?: string;
  instructorId?: string;
  companyId?: string;
  examNumber?: string;
  examName?: string;
  value: number;
  generatedAt: string;
  dueDate: string;
  paidAt?: string;
  status?: 'Pending' | 'Paid' | 'Overdue' | 'Cancelled';
  notes?: string;
  autoGenerated?: boolean;
  triggerAction?: string;
}

export type UpdateCostEntryDTO = Partial<CreateCostEntryDTO>;

type ApiCostEntry = {
  id: string;
  code: string;
  auditableCostId: string;
  costCriterionId?: string;
  studentId?: string;
  classId?: string;
  supplierId?: string;
  instructorId?: string;
  companyId?: string;
  examNumber?: string;
  examName?: string;
  value: number | string;
  generatedAt: string;
  dueDate: string;
  paidAt?: string | null;
  status: 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELLED';
  notes?: string;
  autoGenerated: boolean;
  triggerAction?: string;
  createdAt: string;
  updatedAt: string;
};

export interface CreateCostCriterionDTO {
  name: string;
  frequency: CostCriterion['frequency'];
  linkage: CostCriterion['linkage'];
  dueCriterion: CostCriterion['dueCriterion'];
  daysUntilDue?: number;
  monthlyClosingDay?: number;
  daysAfterClosing?: number;
  active?: boolean;
  notes?: string;
  triggers?: string[];
}

export type UpdateCostCriterionDTO = Partial<CreateCostCriterionDTO>;

type ApiCostCriterion = {
  id: string;
  code: string;
  name: string;
  frequency: 'MONTHLY' | 'DAILY' | 'ONE_TIME';
  linkage: 'ENROLLED_STUDENT' | 'NOT_LINKED' | 'INSTRUCTOR';
  dueCriterion:
    | 'COURSE_END_DATE'
    | 'THIRTY_DAYS_AFTER_END'
    | 'MONTHLY_CLOSING'
    | 'SPECIFIC_DATE'
    | 'NO_DUE';
  daysUntilDue?: number;
  monthlyClosingDay?: number;
  daysAfterClosing?: number;
  isActive: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
};

const TRIGGERS_PREFIX = '__TRIGGERS__=';

function mapFrequencyFromApi(value: ApiCostCriterion['frequency']): CostCriterion['frequency'] {
  if (value === 'MONTHLY') return 'Monthly';
  if (value === 'DAILY') return 'Daily';
  return 'OneTime';
}

function mapFrequencyToApi(value: CostCriterion['frequency']): ApiCostCriterion['frequency'] {
  if (value === 'Monthly') return 'MONTHLY';
  if (value === 'Daily') return 'DAILY';
  return 'ONE_TIME';
}

function mapLinkageFromApi(value: ApiCostCriterion['linkage']): CostCriterion['linkage'] {
  if (value === 'ENROLLED_STUDENT') return 'EnrolledStudent';
  if (value === 'INSTRUCTOR') return 'Instructor';
  return 'NotLinked';
}

function mapLinkageToApi(value: CostCriterion['linkage']): ApiCostCriterion['linkage'] {
  if (value === 'EnrolledStudent') return 'ENROLLED_STUDENT';
  if (value === 'Instructor') return 'INSTRUCTOR';
  return 'NOT_LINKED';
}

function mapDueCriterionFromApi(value: ApiCostCriterion['dueCriterion']): CostCriterion['dueCriterion'] {
  if (value === 'COURSE_END_DATE') return 'CourseEndDate';
  if (value === 'THIRTY_DAYS_AFTER_END') return '30DaysAfterEnd';
  if (value === 'MONTHLY_CLOSING') return 'MonthlyClosing';
  if (value === 'SPECIFIC_DATE') return 'SpecificDate';
  return 'NoDue';
}

function mapDueCriterionToApi(value: CostCriterion['dueCriterion']): ApiCostCriterion['dueCriterion'] {
  if (value === 'CourseEndDate') return 'COURSE_END_DATE';
  if (value === '30DaysAfterEnd') return 'THIRTY_DAYS_AFTER_END';
  if (value === 'MonthlyClosing') return 'MONTHLY_CLOSING';
  if (value === 'SpecificDate') return 'SPECIFIC_DATE';
  return 'NO_DUE';
}

function parseCriterionNotes(notes?: string): { notes?: string; triggers?: string[] } {
  if (!notes) return {};
  const line = notes
    .split('\n')
    .map((item) => item.trim())
    .find((item) => item.startsWith(TRIGGERS_PREFIX));

  if (!line) return { notes };

  try {
    const parsed = JSON.parse(line.slice(TRIGGERS_PREFIX.length)) as {
      triggers?: string[];
      notes?: string;
    };

    const plain = notes
      .split('\n')
      .filter((item) => !item.trim().startsWith(TRIGGERS_PREFIX))
      .join('\n')
      .trim();

    return {
      triggers: Array.isArray(parsed.triggers) ? parsed.triggers : [],
      notes: parsed.notes || plain || undefined,
    };
  } catch {
    return { notes };
  }
}

function serializeCriterionNotes(notes?: string, triggers?: string[]): string | undefined {
  const payload = JSON.stringify({
    notes: notes?.trim() || undefined,
    triggers: triggers && triggers.length > 0 ? triggers : [],
  });

  const serialized = `${TRIGGERS_PREFIX}${payload}`;
  return serialized;
}

function mapCriterionFromApi(item: ApiCostCriterion): CostCriterion {
  const parsed = parseCriterionNotes(item.notes);

  return {
    id: item.id,
    code: item.code,
    name: item.name,
    frequency: mapFrequencyFromApi(item.frequency),
    linkage: mapLinkageFromApi(item.linkage),
    dueCriterion: mapDueCriterionFromApi(item.dueCriterion),
    daysUntilDue: item.daysUntilDue ?? undefined,
    monthlyClosingDay: item.monthlyClosingDay ?? undefined,
    daysAfterClosing: item.daysAfterClosing ?? undefined,
    active: item.isActive,
    triggers: parsed.triggers,
    notes: parsed.notes,
    createdAt: item.createdAt,
    updatedAt: item.updatedAt,
  };
}

function mapCostEntryStatusFromApi(status: ApiCostEntry['status']): CostEntry['status'] {
  if (status === 'PAID') return 'Paid';
  if (status === 'OVERDUE') return 'Overdue';
  if (status === 'CANCELLED') return 'Cancelled';
  return 'Pending';
}

function mapCostEntryStatusToApi(
  status: NonNullable<CreateCostEntryDTO['status']>
): ApiCostEntry['status'] {
  if (status === 'Paid') return 'PAID';
  if (status === 'Overdue') return 'OVERDUE';
  if (status === 'Cancelled') return 'CANCELLED';
  return 'PENDING';
}

function mapCostEntryFromApi(item: ApiCostEntry): CostEntry {
  return {
    id: item.id,
    code: item.code,
    auditableCostId: item.auditableCostId,
    costCriterionId: item.costCriterionId || undefined,
    studentId: item.studentId || undefined,
    classId: item.classId || undefined,
    supplierId: item.supplierId || undefined,
    instructorId: item.instructorId || undefined,
    companyId: item.companyId || undefined,
    examNumber: item.examNumber || undefined,
    examName: item.examName || undefined,
    value: Number(item.value),
    generatedAt: item.generatedAt,
    dueDate: item.dueDate,
    paidAt: item.paidAt || undefined,
    status: mapCostEntryStatusFromApi(item.status),
    notes: item.notes || undefined,
    autoGenerated: item.autoGenerated,
    triggerAction: item.triggerAction || undefined,
    createdAt: item.createdAt,
    updatedAt: item.updatedAt,
  };
}

export interface CreateCostDTO {
  category: CostCategory;
  description: string;
  amount: number;
  period: string; // ISO date string
  supplierId?: string;
  companyId?: string;
  instructorId?: string;
  linkType?: 'none' | 'company' | 'instructor';
  isRecurring?: boolean;
  isAuditable?: boolean;
  notes?: string;
}

export type UpdateCostDTO = Partial<CreateCostDTO>;

export interface PaginatedResponse<T> {
  data: T[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

export interface CostFilters {
  category?: CostCategory;
  isAuditable?: boolean;
  startDate?: Date;
  endDate?: Date;
  page?: number;
  limit?: number;
}

export const costsService = {
  /**
   * Busca todos os custos (paginado)
   */
  getAll: async (filters?: CostFilters): Promise<PaginatedResponse<Cost>> => {
    const params: Record<string, string | number | boolean> = {
      page: filters?.page || 1,
      limit: filters?.limit || 20,
    };

    if (filters?.category) params.category = filters.category;
    if (filters?.isAuditable !== undefined) params.isAuditable = filters.isAuditable;
    if (filters?.startDate) params.startDate = filters.startDate.toISOString();
    if (filters?.endDate) params.endDate = filters.endDate.toISOString();

    const response = await api.get('/costs', { params });
    return response.data;
  },

  /**
   * Busca um custo por ID
   */
  getById: async (id: string): Promise<Cost> => {
    const response = await api.get(`/costs/${id}`);
    return response.data;
  },

  /**
   * Cria um novo custo
   */
  create: async (data: CreateCostDTO): Promise<Cost> => {
    const response = await api.post('/costs', data);
    return response.data;
  },

  /**
   * Atualiza um custo existente
   */
  update: async (id: string, data: UpdateCostDTO): Promise<Cost> => {
    const response = await api.put(`/costs/${id}`, data);
    return response.data;
  },

  /**
   * Remove um custo (soft delete)
   */
  delete: async (id: string): Promise<void> => {
    await api.delete(`/costs/${id}`);
  },

  /**
   * Busca custos auditáveis (para vincular a cursos)
   */
  getAuditable: async (): Promise<Cost[]> => {
    const response = await api.get('/costs', { 
      params: { isAuditable: true, limit: 100 } 
    });
    return response.data.data || response.data;
  },

  /**
   * Busca custos por categoria
   */
  getByCategory: async (category: CostCategory): Promise<Cost[]> => {
    const response = await api.get('/costs', { 
      params: { category, limit: 100 } 
    });
    return response.data.data || response.data;
  },

  getCriteria: async (): Promise<CostCriterion[]> => {
    const response = await api.get('/costs/criteria', {
      params: { page: 1, limit: 200 },
    });
    const data = response.data?.data || [];
    return data.map((item: ApiCostCriterion) => mapCriterionFromApi(item));
  },

  createCriterion: async (data: CreateCostCriterionDTO): Promise<CostCriterion> => {
    const response = await api.post('/costs/criteria', {
      name: data.name,
      frequency: mapFrequencyToApi(data.frequency),
      linkage: mapLinkageToApi(data.linkage),
      dueCriterion: mapDueCriterionToApi(data.dueCriterion),
      daysUntilDue: data.daysUntilDue,
      monthlyClosingDay: data.monthlyClosingDay,
      daysAfterClosing: data.daysAfterClosing,
      notes: serializeCriterionNotes(data.notes, data.triggers),
    });
    return mapCriterionFromApi(response.data);
  },

  updateCriterion: async (id: string, data: UpdateCostCriterionDTO): Promise<CostCriterion> => {
    const response = await api.put(`/costs/criteria/${id}`, {
      ...(data.name !== undefined && { name: data.name }),
      ...(data.frequency !== undefined && { frequency: mapFrequencyToApi(data.frequency) }),
      ...(data.linkage !== undefined && { linkage: mapLinkageToApi(data.linkage) }),
      ...(data.dueCriterion !== undefined && { dueCriterion: mapDueCriterionToApi(data.dueCriterion) }),
      ...(data.daysUntilDue !== undefined && { daysUntilDue: data.daysUntilDue }),
      ...(data.monthlyClosingDay !== undefined && { monthlyClosingDay: data.monthlyClosingDay }),
      ...(data.daysAfterClosing !== undefined && { daysAfterClosing: data.daysAfterClosing }),
      ...(data.active !== undefined && { isActive: data.active }),
      notes: serializeCriterionNotes(data.notes, data.triggers),
    });
    return mapCriterionFromApi(response.data);
  },

  deleteCriterion: async (id: string): Promise<void> => {
    await api.delete(`/costs/criteria/${id}`);
  },

  getEntries: async (page = 1, limit = 500): Promise<PaginatedResponse<CostEntry>> => {
    const response = await api.get('/costs/entries', { params: { page, limit } });
    const payload = response.data;
    return {
      data: (payload.data || []).map((item: ApiCostEntry) => mapCostEntryFromApi(item)),
      meta: payload.meta,
    };
  },

  createEntry: async (data: CreateCostEntryDTO): Promise<CostEntry> => {
    const response = await api.post('/costs/entries', {
      ...data,
      status: mapCostEntryStatusToApi(data.status || 'Pending'),
    });
    return mapCostEntryFromApi(response.data);
  },

  updateEntry: async (id: string, data: UpdateCostEntryDTO): Promise<CostEntry> => {
    const response = await api.put(`/costs/entries/${id}`, {
      ...data,
      ...(data.status !== undefined && { status: mapCostEntryStatusToApi(data.status) }),
    });
    return mapCostEntryFromApi(response.data);
  },

  payEntry: async (id: string, paidAt?: string): Promise<CostEntry> => {
    const response = await api.post(`/costs/entries/${id}/pay`, { paidAt });
    return mapCostEntryFromApi(response.data);
  },

  deleteEntry: async (id: string): Promise<void> => {
    await api.delete(`/costs/entries/${id}`);
  },

  /**
   * Busca resumo de custos por período
   */
  getSummaryByPeriod: async (startDate: Date, endDate: Date): Promise<{
    total: number;
    byCategory: Record<CostCategory, number>;
    recurring: number;
    oneTime: number;
  }> => {
    const response = await api.get('/costs', {
      params: {
        startDate: startDate.toISOString(),
        endDate: endDate.toISOString(),
        limit: 1000,
      },
    });

    const costs: Cost[] = response.data.data || response.data;
    
    const summary = {
      total: 0,
      byCategory: {} as Record<CostCategory, number>,
      recurring: 0,
      oneTime: 0,
    };

    costs.forEach((cost) => {
      const amount = Number(cost.amount);
      summary.total += amount;
      
      if (!summary.byCategory[cost.category]) {
        summary.byCategory[cost.category] = 0;
      }
      summary.byCategory[cost.category] += amount;
      
      if (cost.isRecurring) {
        summary.recurring += amount;
      } else {
        summary.oneTime += amount;
      }
    });

    return summary;
  },
};
