import { z } from 'zod';

const CostEntryStatusSchema = z.enum(['PENDING', 'PAID', 'OVERDUE', 'CANCELLED']);

export const CreateCostEntrySchema = z.object({
  id: z.string().uuid().optional(),
  code: z.string().min(2).max(32),
  auditableCostId: z.string().uuid(),
  costCriterionId: z.string().uuid().optional(),
  studentId: z.string().uuid().optional(),
  classId: z.string().uuid().optional(),
  supplierId: z.string().uuid().optional(),
  instructorId: z.string().uuid().optional(),
  companyId: z.string().uuid().optional(),
  examNumber: z.string().max(100).optional(),
  examName: z.string().max(255).optional(),
  value: z.number(),
  generatedAt: z.string(),
  dueDate: z.string(),
  paidAt: z.string().optional(),
  status: CostEntryStatusSchema.optional(),
  notes: z.string().optional(),
  autoGenerated: z.boolean().optional(),
  triggerAction: z.string().max(120).optional(),
});

export type CreateCostEntryDto = z.infer<typeof CreateCostEntrySchema>;
