import { create } from 'zustand';
import { useClassesStore } from '@/stores/classes.store';
import { useCompaniesStore } from '@/stores/companies.store';
import { useCoursesStore } from '@/stores/courses.store';
import { useSettingsStore } from '@/stores/settings.store';
import { costsService } from '@/services/costs.service';

// ============================================
// SMCORP - Costs Store (Module 08)
// Cost Management and Financial
// ============================================

// Types
export type CostTriggerAction =
  | 'NewEnrollment'
  | 'StatusScheduled'
  | 'StatusConfirm'
  | 'StatusConfirmed'
  | 'StatusPresent'
  | 'FirstPayment'
  | 'PaymentConfirmed'
  | 'AllDocsApproved'
  | 'DocApproved'
  | 'ExamScheduled'
  | 'ExamCancelled'
  | 'ExamPassed'
  | 'ExamFailed'
  | 'ExamNoShow'
  | 'StudentEdited'
  | 'StudentReplaced'
  | 'StudentTransferred'
  | 'AttendanceMarked'
  | 'LinkSent'
  | 'InstructorLinkedToClass'
  | 'InstructorAttendance'
  | 'InstructorAssignedToExam';

export interface AuditableCost {
  id: string;
  code: string;
  name: string;
  value: number;
  supplierId?: string;
  companyId?: string;
  costCriterionId?: string;
  linkType?: 'none' | 'company' | 'instructor';
  instructorId?: string;
  active: boolean;
}

export interface CostCriterion {
  id: string;
  code: string;
  name: string;
  frequency: 'Monthly' | 'Daily' | 'OneTime';
  linkage: 'EnrolledStudent' | 'NotLinked' | 'Instructor';
  dueCriterion:
    | 'CourseEndDate'
    | '30DaysAfterEnd'
    | 'MonthlyClosing'
    | 'SpecificDate'
    | 'NoDue';
  daysUntilDue?: number;
  monthlyClosingDay?: number;
  daysAfterClosing?: number;
  triggers?: CostTriggerAction[];
  active: boolean;
  createdAt: string;
}

export interface CostEntry {
  id: string;
  code: string;
  auditableCostId: string;
  costCriterionId?: string;
  studentId?: string;
  classId?: string;
  courseId?: string;
  supplierId?: string;
  instructorId?: string;
  examNumber?: string;
  examName?: string;
  value: number;
  generatedAt: string;
  dueDate: string;
  status: 'Pending' | 'Paid' | 'Overdue' | 'Cancelled';
  paidAt?: string;
  notes?: string;
  autoGenerated: boolean;
  triggerAction?: CostTriggerAction;
}

interface CostsState {
  // State
  auditableCosts: AuditableCost[];
  costCriteria: CostCriterion[];
  costEntries: CostEntry[];
  loading: boolean;
  error: string | null;

  // Filters
  filters: {
    search: string;
    status: CostEntry['status'] | null;
    supplierId: string | null;
    classId: string | null;
    startDate: string | null;
    endDate: string | null;
  };

  // Counters for codes
  costCounter: number;
  criterionCounter: number;
  entryCounter: number;

  // Setters
  setAuditableCosts: (costs: AuditableCost[]) => void;
  setCostCriteria: (criteria: CostCriterion[]) => void;
  setCostEntries: (entries: CostEntry[]) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  setFilters: (filters: Partial<CostsState['filters']>) => void;

  // CRUD Auditable Costs
  addAuditableCost: (cost: Omit<AuditableCost, 'id' | 'code'>) => AuditableCost;
  updateAuditableCost: (id: string, cost: Partial<AuditableCost>) => void;
  deleteAuditableCost: (id: string) => void;

  // CRUD Cost Criteria
  addCostCriterion: (criterion: Omit<CostCriterion, 'id' | 'code' | 'createdAt'>) => CostCriterion;
  updateCostCriterion: (id: string, criterion: Partial<CostCriterion>) => void;
  deleteCostCriterion: (id: string) => void;

  // CRUD Cost Entries
  addCostEntry: (entry: Omit<CostEntry, 'id' | 'code'>) => CostEntry;
  updateCostEntry: (id: string, entry: Partial<CostEntry>) => void;
  deleteCostEntry: (id: string) => void;

  // Specific Actions
  payCostEntry: (id: string, paidAt?: string) => void;
  cancelCostEntry: (id: string) => void;
  deleteCostEntriesByStudentId: (studentId: string) => void;
  deleteCostEntriesByExam: (params: {
    instructorId: string;
    examNumber: string;
    classId?: string;
  }) => void;
  deleteCostEntriesByExamNumber: (params: {
    examNumber: string;
    classId?: string;
  }) => void;
  deleteCostEntriesByStudentExam: (params: {
    studentId: string;
    examNumber: string;
    classId?: string;
  }) => void;
  deleteCostEntriesByInstructorClass: (params: {
    instructorId: string;
    classId: string;
  }) => void;
  cancelCostEntriesByAction: (params: {
    action: CostTriggerAction;
    studentId?: string;
    classId?: string;
    instructorId?: string;
    examNumber?: string;
  }) => void;
  cleanupOrphanCostEntries: () => number;
  renumberCostEntries: () => void;
  verifyExamCostsForDeletion: (params: {
    studentId: string;
    instructorId: string;
    examNumber: string;
    classId?: string;
    studentIdsInExam: string[];
  }) => { shouldDelete: boolean; costs: CostEntry[] };
  linkInstructorCost: (costId: string, instructorId: string) => void;
  unlinkInstructorCost: (costId: string) => void;
  triggerInstructorAutomaticCosts: (params: {
    instructorId: string;
    classId?: string;
    date?: string;
  }) => CostEntry[];
  triggerInstructorExamCosts: (params: {
    instructorId: string;
    classId?: string;
    examNumber?: string;
    examName?: string;
  }) => CostEntry[];
  triggerAutomaticCosts: (
    action: CostTriggerAction,
    context: {
      studentId?: string;
      classId?: string;
      courseId?: string;
      companyId?: string;
      studentExtraProductIds?: string[];
      instructorId?: string;
      examNumber?: string;
      examName?: string;
    }
  ) => CostEntry[];

  // Batch generation
  addBatchCostEntries: (entries: Omit<CostEntry, 'id' | 'code'>[]) => CostEntry[];

  // Helpers
  getFilteredEntries: () => CostEntry[];
  getEntriesByStatus: (status: CostEntry['status']) => CostEntry[];
  getTotalPending: () => number;
  getTotalPaid: () => number;

  // Reset
  reset: () => void;
}

const initialState = {
  auditableCosts: [] as AuditableCost[],
  costCriteria: [] as CostCriterion[],
  costEntries: [] as CostEntry[],
  loading: false,
  error: null as string | null,
  filters: {
    search: '',
    status: null as CostEntry['status'] | null,
    supplierId: null as string | null,
    classId: null as string | null,
    startDate: null as string | null,
    endDate: null as string | null,
  },
  costCounter: 1,
  criterionCounter: 1,
  entryCounter: 1,
};

function toIsoDate(date?: string): string | undefined {
  if (!date) return undefined;
  if (date.includes('T')) return date;
  return `${date}T00:00:00.000Z`;
}

function buildUniqueEntryCode(sequence: number): string {
  return `CE${Date.now()}${String(sequence).padStart(3, '0')}`;
}

function persistCreateEntry(entry: CostEntry) {
  void costsService.createEntry({
    id: entry.id,
    code: entry.code,
    auditableCostId: entry.auditableCostId,
    costCriterionId: entry.costCriterionId,
    studentId: entry.studentId,
    classId: entry.classId,
    supplierId: entry.supplierId,
    instructorId: entry.instructorId,
    examNumber: entry.examNumber,
    examName: entry.examName,
    value: entry.value,
    generatedAt: toIsoDate(entry.generatedAt) || new Date().toISOString(),
    dueDate: toIsoDate(entry.dueDate) || new Date().toISOString(),
    paidAt: toIsoDate(entry.paidAt),
    status: entry.status,
    notes: entry.notes,
    autoGenerated: entry.autoGenerated,
    triggerAction: entry.triggerAction,
  }).catch(() => undefined);
}

function persistUpdateEntry(id: string, entryData: Partial<CostEntry>) {
  void costsService
    .updateEntry(id, {
      ...(entryData.code !== undefined && { code: entryData.code }),
      ...(entryData.status !== undefined && { status: entryData.status }),
      ...(entryData.paidAt !== undefined && { paidAt: toIsoDate(entryData.paidAt) }),
      ...(entryData.notes !== undefined && { notes: entryData.notes }),
    })
    .catch(() => undefined);
}

function persistDeleteEntries(ids: string[]) {
  if (ids.length === 0) return;
  void Promise.all(ids.map((id) => costsService.deleteEntry(id))).catch(() => undefined);
}

export const useCostsStore = create<CostsState>()(
  (set, get) => ({
      ...initialState,

      // Setters
      setAuditableCosts: (costs) => set({ auditableCosts: costs }),
      setCostCriteria: (criteria) => set({ costCriteria: criteria }),
      setCostEntries: (entries) => set({ costEntries: entries }),
      setLoading: (loading) => set({ loading }),
      setError: (error) => set({ error }),
      setFilters: (filters) =>
        set((state) => ({ filters: { ...state.filters, ...filters } })),

      // CRUD Auditable Costs
      addAuditableCost: (costData) => {
        const { costCounter, auditableCosts } = get();
        const code = `AC${String(costCounter).padStart(4, '0')}`;
        const id = `cost-${Date.now()}`;
        const cost: AuditableCost = { ...costData, id, code };
        set({
          auditableCosts: [...auditableCosts, cost],
          costCounter: costCounter + 1,
        });
        return cost;
      },

      updateAuditableCost: (id, costData) =>
        set((state) => ({
          auditableCosts: state.auditableCosts.map((c) =>
            c.id === id ? { ...c, ...costData } : c
          ),
        })),

      deleteAuditableCost: (id) =>
        set((state) => ({
          auditableCosts: state.auditableCosts.filter((c) => c.id !== id),
          costEntries: state.costEntries.filter((entry) => entry.auditableCostId !== id),
        })),

      // CRUD Cost Criteria
      addCostCriterion: (criterionData) => {
        const { criterionCounter, costCriteria } = get();
        const code = `CR${String(criterionCounter).padStart(4, '0')}`;
        const id = `criterion-${Date.now()}`;
        const createdAt = new Date().toISOString().split('T')[0];
        const criterion: CostCriterion = { ...criterionData, id, code, createdAt };
        set({
          costCriteria: [...costCriteria, criterion],
          criterionCounter: criterionCounter + 1,
        });
        return criterion;
      },

      updateCostCriterion: (id, criterionData) =>
        set((state) => ({
          costCriteria: state.costCriteria.map((c) =>
            c.id === id ? { ...c, ...criterionData } : c
          ),
        })),

      deleteCostCriterion: (id) =>
        set((state) => ({
          costCriteria: state.costCriteria.filter((c) => c.id !== id),
        })),

      // CRUD Cost Entries
      addCostEntry: (entryData) => {
        const { entryCounter, costEntries } = get();
        const code = buildUniqueEntryCode(entryCounter);
        const id = crypto.randomUUID();
        const entry: CostEntry = { ...entryData, id, code };
        set({
          costEntries: [...costEntries, entry],
          entryCounter: entryCounter + 1,
        });
        persistCreateEntry(entry);
        return entry;
      },

      updateCostEntry: (id, entryData) => {
        set((state) => ({
          costEntries: state.costEntries.map((e) =>
            e.id === id ? { ...e, ...entryData } : e
          ),
        }));
        persistUpdateEntry(id, entryData);
      },

      deleteCostEntry: (id) => {
        set((state) => ({
          costEntries: state.costEntries.filter((e) => e.id !== id),
        }));
        persistDeleteEntries([id]);
      },

      // Specific Actions
      payCostEntry: (id, paidAt) => {
        const resolvedPaidAt = paidAt || new Date().toISOString().split('T')[0];
        set((state) => ({
          costEntries: state.costEntries.map((e) =>
            e.id === id
              ? {
                  ...e,
                  status: 'Paid' as const,
                  paidAt: resolvedPaidAt,
                }
              : e
          ),
        }));
        persistUpdateEntry(id, { status: 'Paid', paidAt: resolvedPaidAt });
      },

      cancelCostEntry: (id) => {
        set((state) => ({
          costEntries: state.costEntries.map((e) =>
            e.id === id ? { ...e, status: 'Cancelled' as const } : e
          ),
        }));
        persistUpdateEntry(id, { status: 'Cancelled' });
      },

      deleteCostEntriesByStudentId: (studentId) => {
        const ids = get().costEntries
          .filter((entry) => entry.studentId === studentId)
          .map((entry) => entry.id);
        set((state) => ({
          costEntries: state.costEntries.filter((entry) => entry.studentId !== studentId),
        }));
        persistDeleteEntries(ids);
      },

      deleteCostEntriesByExam: ({ instructorId, examNumber, classId }) => {
        const ids = get().costEntries
          .filter((entry) => {
            if (entry.instructorId !== instructorId) return false;
            if (entry.examNumber !== examNumber) return false;
            if (classId && entry.classId !== classId) return false;
            return true;
          })
          .map((entry) => entry.id);
        set((state) => ({
          costEntries: state.costEntries.filter((entry) => {
            if (entry.instructorId !== instructorId) return true;
            if (entry.examNumber !== examNumber) return true;
            if (classId && entry.classId !== classId) return true;
            return false;
          }),
        }));
        persistDeleteEntries(ids);
      },

      deleteCostEntriesByExamNumber: ({ examNumber, classId }) => {
        const ids = get().costEntries
          .filter((entry) => {
            if (entry.examNumber !== examNumber) return false;
            if (classId && entry.classId !== classId) return false;
            return true;
          })
          .map((entry) => entry.id);
        set((state) => ({
          costEntries: state.costEntries.filter((entry) => {
            if (entry.examNumber !== examNumber) return true;
            if (classId && entry.classId !== classId) return true;
            return false;
          }),
        }));
        persistDeleteEntries(ids);
      },

      deleteCostEntriesByStudentExam: ({ studentId, examNumber, classId }) => {
        const ids = get().costEntries
          .filter((entry) => {
            if (entry.studentId !== studentId) return false;
            if (entry.examNumber !== examNumber) return false;
            if (classId && entry.classId !== classId) return false;
            return true;
          })
          .map((entry) => entry.id);
        set((state) => ({
          costEntries: state.costEntries.filter((entry) => {
            if (entry.studentId !== studentId) return true;
            if (entry.examNumber !== examNumber) return true;
            if (classId && entry.classId !== classId) return true;
            return false;
          }),
        }));
        persistDeleteEntries(ids);
      },

      deleteCostEntriesByInstructorClass: ({ instructorId, classId }) => {
        const ids = get().costEntries
          .filter((entry) => entry.instructorId === instructorId && entry.classId === classId)
          .map((entry) => entry.id);
        set((state) => ({
          costEntries: state.costEntries.filter((entry) => {
            if (entry.instructorId !== instructorId) return true;
            if (entry.classId !== classId) return true;
            return false;
          }),
        }));
        persistDeleteEntries(ids);
      },

      cancelCostEntriesByAction: ({
        action,
        studentId,
        classId,
        instructorId,
        examNumber,
      }) => {
        const affectedIds = get().costEntries
          .filter((entry) => {
            if (entry.triggerAction !== action) return false;
            if (studentId && entry.studentId !== studentId) return false;
            if (classId && entry.classId !== classId) return false;
            if (instructorId && entry.instructorId !== instructorId) return false;
            if (examNumber && entry.examNumber !== examNumber) return false;
            return true;
          })
          .map((entry) => entry.id);

        set((state) => ({
          costEntries: state.costEntries.map((entry) => {
            if (entry.triggerAction !== action) return entry;
            if (studentId && entry.studentId !== studentId) return entry;
            if (classId && entry.classId !== classId) return entry;
            if (instructorId && entry.instructorId !== instructorId) return entry;
            if (examNumber && entry.examNumber !== examNumber) return entry;
            return { ...entry, status: 'Cancelled' as const };
          }),
        }));

        affectedIds.forEach((id) => {
          persistUpdateEntry(id, { status: 'Cancelled' });
        });
      },

      cleanupOrphanCostEntries: () => {
        const { costEntries, auditableCosts, costCriteria } = get();
        const auditableIds = new Set(auditableCosts.map((cost) => cost.id));
        const criterionIds = new Set(costCriteria.map((criterion) => criterion.id));

        const nextEntries = costEntries.filter((entry) => {
          if (!auditableIds.has(entry.auditableCostId)) return false;
          if (entry.costCriterionId && !criterionIds.has(entry.costCriterionId)) return false;
          return true;
        });

        const removedCount = costEntries.length - nextEntries.length;
        if (removedCount > 0) {
          set({ costEntries: nextEntries });
        }
        return removedCount;
      },

      renumberCostEntries: () => {
        const { costEntries } = get();
        const renumberedEntries = costEntries.map((entry, index) => ({
          ...entry,
          code: `CE${String(index + 1).padStart(4, '0')}`,
        }));

        set({
          costEntries: renumberedEntries,
          entryCounter: renumberedEntries.length + 1,
        });

        renumberedEntries.forEach((entry) => {
          persistUpdateEntry(entry.id, { code: entry.code });
        });
      },

      verifyExamCostsForDeletion: ({
        studentId,
        instructorId,
        examNumber,
        classId,
        studentIdsInExam,
      }) => {
        if (studentIdsInExam.filter((id) => id !== studentId).length > 0) {
          return { shouldDelete: false, costs: [] };
        }

        const costs = get().costEntries.filter((entry) => {
          if (entry.instructorId !== instructorId) return false;
          if (entry.examNumber !== examNumber) return false;
          if (classId && entry.classId !== classId) return false;
          return true;
        });

        return { shouldDelete: true, costs };
      },

      linkInstructorCost: (costId, instructorId) => {
        void costsService.update(costId, {
          linkType: 'instructor',
          instructorId,
          companyId: undefined,
        }).catch(() => undefined);
        set((state) => ({
          auditableCosts: state.auditableCosts.map((cost) =>
            cost.id === costId
              ? {
                  ...cost,
                  linkType: 'instructor',
                  instructorId,
                  companyId: undefined,
                }
              : cost
          ),
        }));
      },

      unlinkInstructorCost: (costId) => {
        void costsService.update(costId, {
          linkType: 'none',
          instructorId: undefined,
        }).catch(() => undefined);
        set((state) => ({
          auditableCosts: state.auditableCosts.map((cost) =>
            cost.id === costId
              ? {
                  ...cost,
                  linkType: 'none',
                  instructorId: undefined,
                }
              : cost
          ),
        }));
      },

      triggerInstructorAutomaticCosts: ({ instructorId, classId }) =>
        get().triggerAutomaticCosts('InstructorAttendance', {
          instructorId,
          classId,
        }),

      triggerInstructorExamCosts: ({ instructorId, classId, examNumber, examName }) =>
        get().triggerAutomaticCosts('InstructorAssignedToExam', {
          instructorId,
          classId,
          examNumber,
          examName,
        }),

      triggerAutomaticCosts: (action, context) => {
        const { costCriteria, auditableCosts, addCostEntry } = get();
        const generatedEntries: CostEntry[] = [];
        const classInfo = context.classId
          ? useClassesStore.getState().classes.find((item) => item.id === context.classId)
          : undefined;

        const isInstructorAction =
          action === 'InstructorLinkedToClass' ||
          action === 'InstructorAttendance' ||
          action === 'InstructorAssignedToExam';

        const courseId = context.courseId || classInfo?.courseId;
        const { courses } = useCoursesStore.getState();
        const { companies } = useCompaniesStore.getState();
        const { extraProducts } = useSettingsStore.getState();
        const course = courseId ? courses.find((item) => item.id === courseId) : undefined;

        const productIds = new Set<string>();
        if (context.companyId && courseId) {
          const company = companies.find((item) => item.id === context.companyId);
          const pricing = company?.pricing?.find((p) => p.courseId === courseId);
          pricing?.includedProductIds?.forEach((id) => productIds.add(id));
        }

        course?.linkedProducts?.forEach((id) => productIds.add(id));
        course?.linkedExtras?.forEach((id) => productIds.add(id));
        context.studentExtraProductIds?.forEach((id) => productIds.add(id));

        // Find criteria that respond to this action
        const activeCriteria = costCriteria.filter(
          (c) => c.active && c.triggers?.includes(action)
        );

        activeCriteria.forEach((criterion) => {
          if (isInstructorAction && criterion.linkage !== 'Instructor') return;
          if (!isInstructorAction && criterion.linkage === 'Instructor') return;

          // Find costs linked to this criterion
          let linkedCosts = auditableCosts.filter(
            (c) => c.costCriterionId === criterion.id && c.active
          );

          if (!isInstructorAction && productIds.size > 0) {
            linkedCosts = linkedCosts.filter((cost) =>
              extraProducts.some(
                (product) =>
                  productIds.has(product.id) &&
                  product.associatedCosts?.includes(cost.id)
              )
            );
          }

          linkedCosts.forEach((cost) => {
            const existingEntry = get().costEntries.some((entry) => {
              if (entry.auditableCostId !== cost.id) return false;
              if (entry.triggerAction !== action) return false;
              if (context.studentId && entry.studentId !== context.studentId) return false;
              if (context.classId && entry.classId !== context.classId) return false;
              if (context.instructorId && entry.instructorId !== context.instructorId) return false;
              if (context.examNumber && entry.examNumber !== context.examNumber) return false;
              return entry.status !== 'Cancelled';
            });

            if (existingEntry) return;

            const dueDate = calculateDueDateForCriterion(criterion, classInfo);
            const entry = addCostEntry({
              auditableCostId: cost.id,
              costCriterionId: criterion.id,
              studentId: context.studentId,
              classId: context.classId,
              courseId: context.courseId,
              supplierId: cost.supplierId,
              instructorId: context.instructorId,
              examNumber: context.examNumber,
              examName: context.examName,
              value: cost.value,
              generatedAt: new Date().toISOString().split('T')[0],
              dueDate,
              status: 'Pending',
              autoGenerated: true,
              triggerAction: action,
            });
            generatedEntries.push(entry);
          });
        });

        return generatedEntries;
      },

      // Batch generation
      addBatchCostEntries: (entriesData) => {
        let { entryCounter, costEntries } = get();
        const created: CostEntry[] = [];

        entriesData.forEach((entryData) => {
          const code = buildUniqueEntryCode(entryCounter);
          const id = crypto.randomUUID();
          const entry: CostEntry = { ...entryData, id, code };
          costEntries = [...costEntries, entry];
          created.push(entry);
          persistCreateEntry(entry);
          entryCounter++;
        });

        set({ costEntries, entryCounter });
        return created;
      },

      // Helpers
      getFilteredEntries: () => {
        const { costEntries, filters } = get();
        return costEntries.filter((entry) => {
          if (filters.status && entry.status !== filters.status) return false;
          if (filters.supplierId && entry.supplierId !== filters.supplierId)
            return false;
          if (filters.classId && entry.classId !== filters.classId) return false;
          if (filters.startDate && entry.dueDate < filters.startDate) return false;
          if (filters.endDate && entry.dueDate > filters.endDate) return false;
          return true;
        });
      },

      getEntriesByStatus: (status) => {
        return get().costEntries.filter((e) => e.status === status);
      },

      getTotalPending: () => {
        return get()
          .costEntries.filter((e) => e.status === 'Pending')
          .reduce((sum, e) => sum + e.value, 0);
      },

      getTotalPaid: () => {
        return get()
          .costEntries.filter((e) => e.status === 'Paid')
          .reduce((sum, e) => sum + e.value, 0);
      },

      // Reset
      reset: () => set(initialState),
    })
);

function calculateDueDateForCriterion(
  criterion: CostCriterion,
  classInfo?: { startDate: string; endDate: string }
): string {
  const today = new Date();
  const fallbackDate = today.toISOString().split('T')[0];
  const classStart = classInfo?.startDate || fallbackDate;
  const classEnd = classInfo?.endDate || fallbackDate;

  if (criterion.dueCriterion === 'CourseEndDate') {
    return classEnd;
  }

  if (criterion.dueCriterion === '30DaysAfterEnd') {
    const endDate = new Date(classEnd + 'T12:00:00');
    endDate.setDate(endDate.getDate() + 30);
    return endDate.toISOString().split('T')[0];
  }

  if (criterion.dueCriterion === 'MonthlyClosing') {
    const baseDate = new Date(classStart + 'T12:00:00');
    const closingDay = criterion.monthlyClosingDay || 5;
    const daysAfter = criterion.daysAfterClosing || 0;
    baseDate.setDate(closingDay);
    baseDate.setDate(baseDate.getDate() + daysAfter);
    return baseDate.toISOString().split('T')[0];
  }

  if (criterion.dueCriterion === 'SpecificDate' && criterion.daysUntilDue) {
    const baseDate = new Date(classStart + 'T12:00:00');
    baseDate.setDate(baseDate.getDate() + criterion.daysUntilDue);
    return baseDate.toISOString().split('T')[0];
  }

  if (criterion.dueCriterion === 'NoDue') {
    const noDue = new Date(today);
    noDue.setFullYear(noDue.getFullYear() + 10);
    return noDue.toISOString().split('T')[0];
  }

  return fallbackDate;
}
