// ============================================
// SMCORP - Smart Cost Generation Utility
// Ported from portalfigma/gerarCustosInteligentes.ts
// ============================================

import type { AuditableCost, CostCriterion, CostEntry } from '@/stores/costs.store';
import type { Student } from '@/stores/students.store';
import type { Class } from '@/stores/classes.store';
import type { Course } from '@/stores/courses.store';
import type { ExtraProduct } from '@/stores/settings.store';

export interface SmartCostResult {
  entries: Omit<CostEntry, 'id' | 'code'>[];
  totalGenerated: number;
  skippedAbsent: number;
  skippedNoProducts: number;
  processedStudents: number;
  processedClasses: number;
}

/**
 * Generates cost entries in batch based on:
 * - Students enrolled in active classes
 * - Products linked to courses and student extras
 * - Costs associated with those products
 * - Cost criteria (frequency, due date rules)
 */
export function generateSmartCosts(
  classes: Class[],
  students: Student[],
  courses: Course[],
  extraProducts: ExtraProduct[],
  auditableCosts: AuditableCost[],
  costCriteria: CostCriterion[],
  existingEntries: CostEntry[]
): SmartCostResult {
  const result: SmartCostResult = {
    entries: [],
    totalGenerated: 0,
    skippedAbsent: 0,
    skippedNoProducts: 0,
    processedStudents: 0,
    processedClasses: 0,
  };

  // Only process active classes
  const activeClasses = classes.filter(c => c.status !== 'Cancelled');

  activeClasses.forEach((classInfo) => {
    const classStudents = students.filter(s => s.classId === classInfo.id && !s.isReplaced);
    
    if (classStudents.length === 0) return;

    result.processedClasses++;
    const course = courses.find(c => c.id === classInfo.courseId);

    classStudents.forEach((student) => {
      result.processedStudents++;

      // Identify student's products (course-linked + extras)
      const productIds = new Set<string>();

      if (course?.linkedProducts) {
        course.linkedProducts.forEach(id => productIds.add(id));
      }
      if (course?.linkedExtras) {
        course.linkedExtras.forEach(id => productIds.add(id));
      }
      if (student.extraProductIds) {
        student.extraProductIds.forEach(id => productIds.add(id));
      }

      // Fallback: match by price
      if (productIds.size === 0 && student.totalValue > 0) {
        const matched = extraProducts.find(p => p.price === student.totalValue);
        if (matched) productIds.add(matched.id);
      }

      if (productIds.size === 0) {
        result.skippedNoProducts++;
        return;
      }

      // For each product, find associated costs
      productIds.forEach((productId) => {
        const product = extraProducts.find(p => p.id === productId);
        if (!product?.associatedCosts || product.associatedCosts.length === 0) return;

        const processedCostIds = new Set<string>();
        const associatedCostIds = product.associatedCosts || [];
        const matchingCosts = auditableCosts.filter(
          (cost) => cost.active && associatedCostIds.includes(cost.id)
        );

        matchingCosts.forEach((cost) => {
          if (processedCostIds.has(cost.id)) return;
          processedCostIds.add(cost.id);

          const criterion = cost.costCriterionId
            ? costCriteria.find((c) => c.id === cost.costCriterionId && c.active)
            : null;

          if (!criterion) return;

          const alreadyExists = existingEntries.some(
            (e) =>
              e.auditableCostId === cost.id &&
              e.studentId === student.id &&
              e.classId === classInfo.id &&
              e.status !== 'Cancelled'
          );

          if (criterion.frequency === 'OneTime') {
            if (alreadyExists) return;

            const dueDate = calculateDueDate(criterion, classInfo);

            result.entries.push({
              auditableCostId: cost.id,
              costCriterionId: criterion.id,
              studentId: student.id,
              classId: classInfo.id,
              courseId: classInfo.courseId,
              supplierId: cost.supplierId,
              value: cost.value,
              generatedAt: new Date().toISOString().split('T')[0],
              dueDate,
              status: 'Pending',
              autoGenerated: true,
              triggerAction: 'NewEnrollment',
              notes: `Turma: ${classInfo.code} | Aluno: ${student.code} ${student.name} | Produto: ${product.name} | Critério: ${criterion.name}`,
            });
            result.totalGenerated++;
            return;
          }

          if (criterion.frequency === 'Daily') {
            const startDate = new Date(
              (classInfo.startDate || new Date().toISOString().split('T')[0]) + 'T12:00:00'
            );
            const endDate = new Date(
              (classInfo.endDate || new Date().toISOString().split('T')[0]) + 'T12:00:00'
            );
            const diffMs = endDate.getTime() - startDate.getTime();
            const totalDays = Math.round(diffMs / (1000 * 60 * 60 * 24)) + 1;

            for (let i = 0; i < totalDays; i++) {
              const dayDate = new Date(startDate);
              dayDate.setDate(dayDate.getDate() + i);
              const dayStr = dayDate.toISOString().split('T')[0];

              const isPresent = student.attendanceByDay?.[dayStr] === true;
              if (!isPresent) {
                result.skippedAbsent++;
                continue;
              }

              const dailyExists = existingEntries.some(
                (e) =>
                  e.auditableCostId === cost.id &&
                  e.studentId === student.id &&
                  e.classId === classInfo.id &&
                  e.dueDate === dayStr &&
                  e.status !== 'Cancelled'
              );
              if (dailyExists) continue;

              const dueDate = calculateDueDateForDay(criterion, dayStr, classInfo);
              const dayLabel = dayDate.toLocaleDateString('pt-BR', {
                day: '2-digit',
                month: '2-digit',
                year: 'numeric',
              });

              result.entries.push({
                auditableCostId: cost.id,
                costCriterionId: criterion.id,
                studentId: student.id,
                classId: classInfo.id,
                courseId: classInfo.courseId,
                supplierId: cost.supplierId,
                value: cost.value,
                generatedAt: new Date().toISOString().split('T')[0],
                dueDate,
                status: 'Pending',
                autoGenerated: true,
                triggerAction: 'AttendanceMarked',
                notes: `Turma: ${classInfo.code} | Aluno: ${student.code} ${student.name} | Produto: ${product.name} | Dia ${dayLabel} | ✅ Presente`,
              });
              result.totalGenerated++;
            }
            return;
          }

          if (criterion.frequency === 'Monthly') {
            const monthsToGenerate = 3;
            const baseDate = new Date(
              (classInfo.startDate || new Date().toISOString().split('T')[0]) + 'T12:00:00'
            );

            for (let i = 0; i < monthsToGenerate; i++) {
              const monthDate = new Date(baseDate);
              monthDate.setMonth(monthDate.getMonth() + i);
              const monthKey = monthDate.toISOString().slice(0, 7);

              const monthlyExists = existingEntries.some(
                (e) =>
                  e.auditableCostId === cost.id &&
                  e.studentId === student.id &&
                  e.classId === classInfo.id &&
                  e.dueDate.startsWith(monthKey) &&
                  e.status !== 'Cancelled'
              );
              if (monthlyExists) continue;

              const dueDate = calculateDueDateMonthly(criterion, monthDate, classInfo);
              const monthLabel = monthDate.toLocaleDateString('pt-BR', {
                month: 'short',
                year: '2-digit',
              });

              result.entries.push({
                auditableCostId: cost.id,
                costCriterionId: criterion.id,
                studentId: student.id,
                classId: classInfo.id,
                courseId: classInfo.courseId,
                supplierId: cost.supplierId,
                value: cost.value,
                generatedAt: new Date().toISOString().split('T')[0],
                dueDate,
                status: i === 0 ? 'Paid' : 'Pending',
                autoGenerated: true,
                triggerAction: 'NewEnrollment',
                notes: `Turma: ${classInfo.code} | Aluno: ${student.code} ${student.name} | Produto: ${product.name} | Mês ${i + 1}/${monthsToGenerate} - ${monthLabel} | Critério: ${criterion.name}`,
              });
              result.totalGenerated++;
            }
          }
        });
      });
    });
  });

  return result;
}

// ============================================
// DUE DATE CALCULATORS
// ============================================

function calculateDueDate(criterion: CostCriterion, classInfo: Class): string {
  if (criterion.dueCriterion === 'CourseEndDate') {
    return classInfo.endDate || classInfo.startDate;
  }
  if (criterion.dueCriterion === '30DaysAfterEnd') {
    const baseEndDate = classInfo.endDate || classInfo.startDate;
    const endDate = new Date(baseEndDate + 'T12:00:00');
    endDate.setDate(endDate.getDate() + 30);
    return endDate.toISOString().split('T')[0];
  }
  if (criterion.dueCriterion === 'MonthlyClosing') {
    const baseDate = new Date((classInfo.startDate || new Date().toISOString().split('T')[0]) + 'T12:00:00');
    const closingDay = criterion.monthlyClosingDay || 5;
    const daysAfter = criterion.daysAfterClosing || 0;
    baseDate.setDate(closingDay);
    baseDate.setDate(baseDate.getDate() + daysAfter);
    return baseDate.toISOString().split('T')[0];
  }
  if (criterion.dueCriterion === 'SpecificDate' && criterion.daysUntilDue) {
    const baseDate = new Date((classInfo.startDate || new Date().toISOString().split('T')[0]) + 'T12:00:00');
    baseDate.setDate(baseDate.getDate() + criterion.daysUntilDue);
    return baseDate.toISOString().split('T')[0];
  }
  return classInfo.startDate || new Date().toISOString().split('T')[0];
}

function calculateDueDateForDay(criterion: CostCriterion, dayStr: string, classInfo: Class): string {
  if (criterion.dueCriterion === 'MonthlyClosing') {
    const baseDate = new Date(dayStr + 'T12:00:00');
    baseDate.setMonth(baseDate.getMonth() + 1);
    const closingDay = criterion.monthlyClosingDay || 5;
    const daysAfter = criterion.daysAfterClosing || 0;
    baseDate.setDate(closingDay);
    baseDate.setDate(baseDate.getDate() + daysAfter);
    return baseDate.toISOString().split('T')[0];
  }
  return dayStr;
}

function calculateDueDateMonthly(criterion: CostCriterion, monthDate: Date, classInfo: Class): string {
  if (criterion.dueCriterion === 'MonthlyClosing') {
    const closingDay = criterion.monthlyClosingDay || 5;
    const daysAfter = criterion.daysAfterClosing || 0;
    const due = new Date(monthDate);
    due.setDate(closingDay);
    due.setDate(due.getDate() + daysAfter);
    return due.toISOString().split('T')[0];
  }
  if (criterion.dueCriterion === 'CourseEndDate') {
    return classInfo.endDate || classInfo.startDate;
  }
  return monthDate.toISOString().split('T')[0];
}
